routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('power', 'Admin\AdminAuth@login');
Route::view('power-qr', 'admin.adminAuth.qr_login');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Config::set('auth.defines', 'admin');
    app()->setLocale('ar');

    //================ Auth ================
//            Route::get('login', 'AdminAuth@login');
    Route::post('power', 'AdminAuth@dologin')->name('admin.login');


    //********************* Auth *********************
    Route::group(['middleware' => 'admin:admin'], function () {

        Route::get('/', function () {
            return view('admin.index');
        });

        Route::get('/test', function () {
            return site_texts('about');
        });


        //================ admin ================
        Route::resource('admin', 'AdminController');
        Route::post('delete-admin', 'AdminController@delete_admin')->name('delete-admin');
        Route::post('update-admin', 'AdminController@update_admin');


        //================ slider ================
        Route::resource('slider', 'SliderController');
        Route::post('delete-slider', 'SliderController@delete_slider')->name('delete-slider');
        Route::post('update-slider', 'SliderController@update_slider');


        //================ contract_advantage ================
        Route::resource('contract_advantage', 'ContractAdvantageController');
        Route::post('delete-contract_advantage', 'ContractAdvantageController@delete_contract_advantage')->name('delete-contract_advantage');
        Route::post('update-contract_advantage', 'ContractAdvantageController@update_contract_advantage');
        Route::get('contract_advantage/add_details/{id}', 'ContractAdvantageController@contract_advantage_add_details');
        Route::post('store_contract_advantage_add_details', 'ContractAdvantageController@store_contract_advantage_add_details');
        Route::post('add-contract_advantage-row', 'ContractAdvantageController@add_contract_advantage_row');
        Route::get('edit_contract_advantage_detail/{id}', 'ContractAdvantageController@editContractAdvantageDetail')->name('edit_contract_advantage_detail');
        Route::put('update_contract_advantage_detail/{id}', 'ContractAdvantageController@updateContractAdvantageDetail')->name('update_contract_advantage_detail');
        Route::post('delete-contract_advantage_details', 'ContractAdvantageController@delete_contract_advantage_details')->name('delete-contract_advantage_details');

        //================ blog ================
        Route::resource('blog', 'BlogController');
        Route::post('delete-blog', 'BlogController@delete_blog')->name('delete-blog');
        Route::post('update-blog', 'BlogController@update_blog');

        //================ video_motion ================
        Route::resource('video_motion', 'VideoMotionController');
        Route::post('delete-video_motion', 'VideoMotionController@delete_video_motion')->name('delete-video_motion');
        Route::post('update-video_motion', 'VideoMotionController@update_video_motion');

        //================ service ================
        Route::resource('service', 'ServiceController');
        Route::post('delete-service', 'ServiceController@delete_service')->name('delete-service');
        Route::post('update-service', 'ServiceController@update_service');

        //service_hosts

        Route::resource('service_hosts', 'ServiceHostController');
        Route::post('delete-service-host', 'ServiceHostController@deleteServiceHost');
        //


        // polices

        Route::resource('polices', 'PolicyController');

        // end polices

        // privacy

        Route::resource('privacy', 'PrivacyController');

        // end privacy

        // roles and conditions

        Route::resource('roles-conditions', 'RoleConditionController');

        // end roles and conditions


        //================ service_text ================
        Route::resource('service_text', 'ServiceTextController');
        Route::post('delete-service_text', 'ServiceTextController@delete_service_text')->name('delete-service_text');
        Route::post('update-service_text', 'ServiceTextController@update_service_text');

        //================ language_allow ================
        Route::resource('language_allow', 'LanguageAllowController');
        Route::post('delete-language_allow', 'LanguageAllowController@delete_language_allow')->name('delete-language_allow');
        Route::post('update-language_allow', 'LanguageAllowController@update_language_allow');

        //================ phone_code_allow ================
        Route::resource('phone_code_allow', 'PhoneCodeAllowController');
        Route::post('delete-phone_code_allow', 'PhoneCodeAllowController@delete_phone_code_allow')->name('delete-phone_code_allow');
        Route::post('update-phone_code_allow', 'PhoneCodeAllowController@update_phone_code_allow');

        //================ site_text ================
        Route::resource('site_text', 'SiteTextController');
        Route::post('delete-site_text', 'SiteTextController@delete_site_text')->name('delete-site_text');
        Route::post('update-site_text', 'SiteTextController@update_site_text');


        //================ offer_detail ================
        Route::resource('offer_detail', 'OfferDetailController');
        Route::post('delete-offer_detail', 'OfferDetailController@delete_offer_detail')->name('delete-offer_detail');
        Route::post('update-offer_detail', 'OfferDetailController@update_offer_detail');
        Route::post('update-prices', 'OfferDetailController@update_prices');


        //================ service_host_detail ================
        Route::resource('service_host_detail', 'ServiceHostDetailController');
        Route::post('delete-service_host_detail', 'ServiceHostDetailController@delete_service_host_detail')->name('delete-service_host_detail');
        Route::post('update-service_host_detail', 'ServiceHostDetailController@update_service_host_detail');


        //================ user ================
        Route::resource('user', 'UserController');
        Route::post('delete-user', 'UserController@delete_user')->name('delete-user');
        Route::post('update-user', 'UserController@update_user');


        //================ client ================
        Route::resource('client', 'ClientController');
        Route::post('delete-client', 'ClientController@delete_client')->name('delete-client');
        Route::post('update-client', 'ClientController@update_client');

        //=================Invoices=====================

        Route::resource('invoices', 'InvoiceController');

        //================ user_program ================
        Route::resource('user_program', 'UserProgramController');
        Route::post('delete-user_program', 'UserProgramController@delete_user_program')->name('delete-user_program');
        Route::post('update-user_program', 'UserProgramController@update_user_program');
        Route::post('update-update_user_program_status', 'UserProgramController@update_user_program_status');
        Route::get('chat', 'UserProgramController@chat');
        Route::post('msg_send', 'UserProgramController@msg_send')->name('msg.send');


        //================ contact ================
        Route::resource('contact', 'ContactController');
        Route::post('delete-contact', 'ContactController@delete_contact')->name('delete-contact');
        Route::post('update-contact', 'ContactController@update_contact');


        //================ settings ================
        Route::get('settings', 'SettingController@edit');
        Route::post('update-setting', 'SettingController@update_setting');



        //================ Teams ================
        Route::resource('teams','TeamController');
        Route::post('teams/delete-team','TeamController@delete');


        Route::post('delete-program', 'ProgramController@deleteProgram');
        Route::resource('programs', 'ProgramController');

        Route::any('logout', 'AdminAuth@logout');

        // test  qr code

        Route::get('/test-qr', 'TestQrCodeController@index');

        Route::view('/test-login-qr', 'admin.test_login_qr');


    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath'],
        'namespace' => 'Website'
    ], function () {

    config(['auth.defaults.guard' => 'web']);


    /* Without auth */
    Route::get('login', 'WebAuth@login');
    Route::post('login_action', 'WebAuth@login_action')->name('login_action');
    Route::get('/', 'HomeController@index');
    Route::get('about', 'AboutController@about');
    Route::get('service', 'ServiceController@services');
    Route::get('service-detail/{service_id}', 'ServiceController@service_detail');
    Route::get('offers', 'OfferController@offers');
    Route::get('blog', 'BlogController@blog');
    Route::get('blog-detail/{id}', 'BlogController@blog_detail');
    Route::get('video-motion', 'VideoMotionController@video_motion');
    Route::get('work_details/{id}', 'VideoMotionController@work_details');
    Route::get('get-video-content', 'VideoMotionController@get_video_content');
    Route::get('order-now', 'OrderController@order_now');
    Route::post('confirm-email', 'OrderController@confirm_email')->name('confirm-email');
    Route::post('send-order-now', 'OrderController@send_order_now')->name('send-order-now');
    Route::get('contact', 'ContactController@contact');
    Route::post('send-contact', 'ContactController@send_contact')->name('send-contact');
    /* Without auth */


    //==============================  rest password =================================
    Route::get('rest-password-form', 'WebAuth@rest_password_form')->name('rest-password-form');
    Route::post('rest-password', 'WebAuth@rest_password')->name('rest-password');
    Route::post('confirm-code', 'WebAuth@confirm_code')->name('confirm-code');
    Route::post('update-password', 'WebAuth@update_password')->name('update-password');
    //==============================  rest password =================================
    Route::view('/training', 'website.pages.training.index');
    Route::get('/team', 'TeamController@index');

    /* With auth */
    Route::group(['middleware' => ['auth']], function () {

        Route::get('profile', 'ProfileController@profile');
        Route::get('get-description', 'ProfileController@getDescription')->name('getUserServiceDescription');
        Route::post('confirm-program', 'ProfileController@confirm_program')->name('confirm-program');
        Route::get('new-apps', 'ProfileController@new_apps');
        Route::post('add-apps', 'ProfileController@add_apps')->name('add-apps');
        Route::get('chat', 'ProfileController@chat');
        Route::post('send_msg', 'ProfileController@msg_send')->name('msg.send_msg');


        Route::get('logout', 'WebAuth@logout');
    });
    /* With auth */

});


//Clear route cache:
Route::get('/clear_cache', function () {
//    $exitCode = Artisan::call('route:cache');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');

    return 'cache cleared';
});

Route::get('/dump-autoload', function () {
    shell_exec('composer dump-autoload');
//    Artisan::call('dump-autoload');
    echo 'dump-autoload complete';
});

Route::get("/storage-link", function () {
    $targetFolder = storage_path("app/public");
    $linkFolder = $_SERVER['DOCUMENT_ROOT'] . '/storage';
    symlink($targetFolder, $linkFolder);
    return 'done';
});

app/Http/Controllers/Admin/PolicyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Traits\CheckAllowedLanguageKeys;
use App\Http\Traits\ViewLanguage;
use App\Models\LanguageAllow;
use App\Models\Policies;
use App\Models\PoliciesTranslation;
use Illuminate\Http\Request;

class PolicyController extends Controller
{

    use CheckAllowedLanguageKeys, ViewLanguage;


    public $page_titles = [
        'index' => 'سياسه الاستخدام',
        'create' => 'سياسه الاستخدام',
        'edit' => '',
    ];

    public function index()
    {

        $policy = Policies::first();


        if ($policy) {

            $language_allows = LanguageAllow::get();
            $title = ' تعديل بيانات ' . $policy->title;
            $this->page_titles['edit'] = $title;
            $view_languages = $this->view_language($policy->policies_trans);


            return view('admin.policy.index', ['page_titles' => $this->page_titles, 'policy' => $policy, 'language_allows' => $language_allows, 'view_languages' => $view_languages]);
        } else {
            $language_allows = LanguageAllow::get();
            $title = ' تعديل بيانات ';
            $this->page_titles['edit'] = $title;

            return view('admin.policy.index', ['page_titles' => $this->page_titles, 'language_allows' => $language_allows, 'policy' => $policy]);
        }

    }//end of index function


    public function store(Request $request)
    {

        try {
            /* =============== check languages =============== */
            if ((!is_array(request()->titles) || !$this->check_allowed_language_keys(request()->titles)) ||
                (!is_array(request()->texts) || !$this->check_allowed_language_keys(request()->texts))) {
                toastr()->warning('رجاء املاء جميع اللغات حتى لا يحدث مشكلة فيما بعد (title)', setting('title'));
                return back()->withInput();
            }


            $policy = Policies::first();


            $data = $request->only('image');
            if (!$policy) {
                if (request()->image != '') {
                    $data['image'] = upload_image('polices', request()->image, 1, 'image', '');
                }

                $policy = Policies::create($data);
                if (count(request()->titles) > 0) {
                    foreach (request()->titles as $lang => $title) {

                        PoliciesTranslation::create([
                            'policy_id' => $policy->id,
                            'title' => $title,
                            'text' => request()->texts[$lang] ? request()->texts[$lang] : null,
                            'lang' => $lang,
                        ]);
                    }
                }
            } else {
                if (request()->image != '') {
                    $data['image'] = upload_image('polices', request()->image, 1, 'image', $policy->image);
                }
                $policy->update($data);


                if ((!is_array(request()->titles) || !$this->check_allowed_language_keys(request()->titles)) ||
                    (!is_array(request()->texts) || !$this->check_allowed_language_keys(request()->texts))) {
                    toastr()->warning('رجاء املاء جميع اللغات حتى لا يحدث مشكلة فيما بعد (title)', setting('title'));
                    return back()->withInput();
                }

                if (count(request()->titles) > 0) {
                    PoliciesTranslation::where([['policy_id', '=', $policy->id]])->delete();
                    foreach (request()->titles as $lang => $title) {
                        PoliciesTranslation::create([
                            'policy_id' => $policy->id,
                            'title' => $title,
                            'text' => request()->texts[$lang] ? request()->texts[$lang] : null,
                            'lang' => $lang,
                        ]);
                    }
                }

            }

        } catch (\Exception $e) {
            toastr()->success($e->getMessage(), 'title');

            return redirect()->back();
        }

        toastr()->success('تم العملية بنجاح', setting('title'));
        return redirect(aurl('polices'));

    }//end of store function

    public function edit($id)
    {


    }//end of edit function


    public function update(Request $request)
    {

        dd($request->all());

    }//end of edit function
}

resources/views/admin/policy/index.blade.php
@extends('admin.layouts.layout')

@php
    $page_title = isset($page_titles['create']) ? $page_titles['create'] : setting('title');
@endphp


@section('page-title')
    {{ $page_title }}
@endsection


@push('admin_css')


@endpush



{{-------------------- start content --------------------}}
@section('content')

    <div class="main-content side-content pt-0">
        <div class="container-fluid">
            <div class="inner-body">

                <div class="page-header">
                    @include('admin.inc.page_header', ['page_title' => $page_title])

                </div>
                <!-- End Page Header -->

                <!--Row-->
                <div class="row">

                    <form action="{{ route('polices.store') }}" method="post" enctype="multipart/form-data">

                        @csrf

                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-body">

                                    <div class="row">
                                        @if(count($language_allows) > 0)
                                            @foreach($language_allows as $language_allow)
                                                <div class="col-md-6 form-group">
                                                    <label>{{'العنوان'}} {{ "(". $language_allow->code .")"}} </label>
                                                    <input name="titles[{{$language_allow->code}}]" value="{{ isset($view_languages[$language_allow->code]) ? $view_languages[$language_allow->code]->title : null }}"
                                                           class="form-control" type="text" placeholder="" required>
                                                </div>
                                            @endforeach
                                        @endif

                                        @if(count($language_allows) > 0)
                                            @foreach($language_allows as $language_allow)
                                                <div class="col-md-6 form-group">
                                                    <label>{{'التفاصيل'}} {{ "(". $language_allow->code .")"}} </label>
                                                    <textarea name="texts[{{$language_allow->code}}]"
                                                              class="form-control" required>{{ isset($view_languages[$language_allow->code]) ? $view_languages[$language_allow->code]->text : null }}</textarea>
                                                </div>
                                            @endforeach
                                        @endif


                                        <div class="col-md-12 form-group">
                                            <label>الصوره</label>
                                            @if($policy)

                                                <input type="file" class="dropify" name="image" data-default-file="{{ GetImg($policy->image) }}">
                                            @else
                                                <input type="file" class="dropify" name="image" data-default-file="">
                                            @endif
                                        </div>

                                    </div>


                                </div>

                                <div class="card-footer">
                                    <div class="col-sm-12">
                                        <button id="submit-form" type="submit" class="btn ripple btn-primary btn-lg">
                                            <i class="fa fa-save loading-submit"></i>
                                            حفظ
                                        </button>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection
{{-------------------- end content --------------------}}


{{-------------------- scripts --------------------}}
@push('admin_css')


@endpush