routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('power', 'Admin\AdminAuth@login');
Route::view('power-qr', 'admin.adminAuth.qr_login');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

    Config::set('auth.defines', 'admin');
    app()->setLocale('ar');

    //================ Auth ================
//            Route::get('login', 'AdminAuth@login');
    Route::post('power', 'AdminAuth@dologin')->name('admin.login');


    //********************* Auth *********************
    Route::group(['middleware' => 'admin:admin'], function () {

        Route::get('/', function () {
            return view('admin.index');
        });

        Route::get('/test', function () {
            return site_texts('about');
        });


        //================ admin ================
        Route::resource('admin', 'AdminController');
        Route::post('delete-admin', 'AdminController@delete_admin')->name('delete-admin');
        Route::post('update-admin', 'AdminController@update_admin');


        //================ slider ================
        Route::resource('slider', 'SliderController');
        Route::post('delete-slider', 'SliderController@delete_slider')->name('delete-slider');
        Route::post('update-slider', 'SliderController@update_slider');


        //================ contract_advantage ================
        Route::resource('contract_advantage', 'ContractAdvantageController');
        Route::post('delete-contract_advantage', 'ContractAdvantageController@delete_contract_advantage')->name('delete-contract_advantage');
        Route::post('update-contract_advantage', 'ContractAdvantageController@update_contract_advantage');
        Route::get('contract_advantage/add_details/{id}', 'ContractAdvantageController@contract_advantage_add_details');
        Route::post('store_contract_advantage_add_details', 'ContractAdvantageController@store_contract_advantage_add_details');
        Route::post('add-contract_advantage-row', 'ContractAdvantageController@add_contract_advantage_row');
        Route::get('edit_contract_advantage_detail/{id}', 'ContractAdvantageController@editContractAdvantageDetail')->name('edit_contract_advantage_detail');
        Route::put('update_contract_advantage_detail/{id}', 'ContractAdvantageController@updateContractAdvantageDetail')->name('update_contract_advantage_detail');
        Route::post('delete-contract_advantage_details', 'ContractAdvantageController@delete_contract_advantage_details')->name('delete-contract_advantage_details');

        //================ blog ================
        Route::resource('blog', 'BlogController');
        Route::post('delete-blog', 'BlogController@delete_blog')->name('delete-blog');
        Route::post('update-blog', 'BlogController@update_blog');

        //================ video_motion ================
        Route::resource('video_motion', 'VideoMotionController');
        Route::post('delete-video_motion', 'VideoMotionController@delete_video_motion')->name('delete-video_motion');
        Route::post('update-video_motion', 'VideoMotionController@update_video_motion');

        //================ service ================
        Route::resource('service', 'ServiceController');
        Route::post('delete-service', 'ServiceController@delete_service')->name('delete-service');
        Route::post('update-service', 'ServiceController@update_service');

        //service_hosts

        Route::resource('service_hosts', 'ServiceHostController');
        Route::post('delete-service-host', 'ServiceHostController@deleteServiceHost');
        //


        // polices

        Route::resource('polices', 'PolicyController');

        // end polices

        // privacy

        Route::resource('privacy', 'PrivacyController');

        // end privacy

        // roles and conditions

        Route::resource('roles-conditions', 'RoleConditionController');

        // end roles and conditions


        //================ service_text ================
        Route::resource('service_text', 'ServiceTextController');
        Route::post('delete-service_text', 'ServiceTextController@delete_service_text')->name('delete-service_text');
        Route::post('update-service_text', 'ServiceTextController@update_service_text');

        //================ language_allow ================
        Route::resource('language_allow', 'LanguageAllowController');
        Route::post('delete-language_allow', 'LanguageAllowController@delete_language_allow')->name('delete-language_allow');
        Route::post('update-language_allow', 'LanguageAllowController@update_language_allow');

        //================ phone_code_allow ================
        Route::resource('phone_code_allow', 'PhoneCodeAllowController');
        Route::post('delete-phone_code_allow', 'PhoneCodeAllowController@delete_phone_code_allow')->name('delete-phone_code_allow');
        Route::post('update-phone_code_allow', 'PhoneCodeAllowController@update_phone_code_allow');

        //================ site_text ================
        Route::resource('site_text', 'SiteTextController');
        Route::post('delete-site_text', 'SiteTextController@delete_site_text')->name('delete-site_text');
        Route::post('update-site_text', 'SiteTextController@update_site_text');


        //================ offer_detail ================
        Route::resource('offer_detail', 'OfferDetailController');
        Route::post('delete-offer_detail', 'OfferDetailController@delete_offer_detail')->name('delete-offer_detail');
        Route::post('update-offer_detail', 'OfferDetailController@update_offer_detail');
        Route::post('update-prices', 'OfferDetailController@update_prices');


        //================ service_host_detail ================
        Route::resource('service_host_detail', 'ServiceHostDetailController');
        Route::post('delete-service_host_detail', 'ServiceHostDetailController@delete_service_host_detail')->name('delete-service_host_detail');
        Route::post('update-service_host_detail', 'ServiceHostDetailController@update_service_host_detail');


        //================ user ================
        Route::resource('user', 'UserController');
        Route::post('delete-user', 'UserController@delete_user')->name('delete-user');
        Route::post('update-user', 'UserController@update_user');


        //================ client ================
        Route::resource('client', 'ClientController');
        Route::post('delete-client', 'ClientController@delete_client')->name('delete-client');
        Route::post('update-client', 'ClientController@update_client');

        //=================Invoices=====================

        Route::resource('invoices', 'InvoiceController');

        //================ user_program ================
        Route::resource('user_program', 'UserProgramController');
        Route::post('delete-user_program', 'UserProgramController@delete_user_program')->name('delete-user_program');
        Route::post('update-user_program', 'UserProgramController@update_user_program');
        Route::post('update-update_user_program_status', 'UserProgramController@update_user_program_status');
        Route::get('chat', 'UserProgramController@chat');
        Route::post('msg_send', 'UserProgramController@msg_send')->name('msg.send');


        //================ contact ================
        Route::resource('contact', 'ContactController');
        Route::post('delete-contact', 'ContactController@delete_contact')->name('delete-contact');
        Route::post('update-contact', 'ContactController@update_contact');


        //================ settings ================
        Route::get('settings', 'SettingController@edit');
        Route::post('update-setting', 'SettingController@update_setting');



        //================ Teams ================
        Route::resource('teams','TeamController');
        Route::post('teams/delete-team','TeamController@delete');


        Route::post('delete-program', 'ProgramController@deleteProgram');
        Route::resource('programs', 'ProgramController');

        Route::any('logout', 'AdminAuth@logout');

        // test  qr code

        Route::get('/test-qr', 'TestQrCodeController@index');

        Route::view('/test-login-qr', 'admin.test_login_qr');


    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath'],
        'namespace' => 'Website'
    ], function () {

    config(['auth.defaults.guard' => 'web']);


    /* Without auth */
    Route::get('login', 'WebAuth@login');
    Route::post('login_action', 'WebAuth@login_action')->name('login_action');
    Route::get('/', 'HomeController@index');
    Route::get('about', 'AboutController@about');
    Route::get('service', 'ServiceController@services');
    Route::get('service-detail/{service_id}', 'ServiceController@service_detail');
    Route::get('offers', 'OfferController@offers');
    Route::get('blog', 'BlogController@blog');
    Route::get('blog-detail/{id}', 'BlogController@blog_detail');
    Route::get('video-motion', 'VideoMotionController@video_motion');
    Route::get('work_details/{id}', 'VideoMotionController@work_details');
    Route::get('get-video-content', 'VideoMotionController@get_video_content');
    Route::get('order-now', 'OrderController@order_now');
    Route::post('confirm-email', 'OrderController@confirm_email')->name('confirm-email');
    Route::post('send-order-now', 'OrderController@send_order_now')->name('send-order-now');
    Route::get('contact', 'ContactController@contact');
    Route::post('send-contact', 'ContactController@send_contact')->name('send-contact');
    /* Without auth */


    //==============================  rest password =================================
    Route::get('rest-password-form', 'WebAuth@rest_password_form')->name('rest-password-form');
    Route::post('rest-password', 'WebAuth@rest_password')->name('rest-password');
    Route::post('confirm-code', 'WebAuth@confirm_code')->name('confirm-code');
    Route::post('update-password', 'WebAuth@update_password')->name('update-password');
    //==============================  rest password =================================
    Route::view('/training', 'website.pages.training.index');
    Route::get('/team', 'TeamController@index');

    /* With auth */
    Route::group(['middleware' => ['auth']], function () {

        Route::get('profile', 'ProfileController@profile');
        Route::get('get-description', 'ProfileController@getDescription')->name('getUserServiceDescription');
        Route::post('confirm-program', 'ProfileController@confirm_program')->name('confirm-program');
        Route::get('new-apps', 'ProfileController@new_apps');
        Route::post('add-apps', 'ProfileController@add_apps')->name('add-apps');
        Route::get('chat', 'ProfileController@chat');
        Route::post('send_msg', 'ProfileController@msg_send')->name('msg.send_msg');


        Route::get('logout', 'WebAuth@logout');
    });
    /* With auth */

});


//Clear route cache:
Route::get('/clear_cache', function () {
//    $exitCode = Artisan::call('route:cache');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');

    return 'cache cleared';
});

Route::get('/dump-autoload', function () {
    shell_exec('composer dump-autoload');
//    Artisan::call('dump-autoload');
    echo 'dump-autoload complete';
});

Route::get("/storage-link", function () {
    $targetFolder = storage_path("app/public");
    $linkFolder = $_SERVER['DOCUMENT_ROOT'] . '/storage';
    symlink($targetFolder, $linkFolder);
    return 'done';
});

resources/views/admin/inc/_css.blade.php
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
<meta name="description" content="Codlop - Dashboard">
<link rel="icon" href="{{asset('dashboard')}}/assets/img/logo-icon.svg" type="image/x-icon">
<title>@yield('page-title')</title>
<link id="style" href="{{asset('dashboard')}}/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="{{asset('dashboard')}}/assets/plugins/web-fonts/icons.css" rel="stylesheet">
<link href="{{asset('dashboard')}}/assets/plugins/web-fonts/font-awesome/font-awesome.min.css" rel="stylesheet">
<link href="{{asset('dashboard')}}/assets/plugins/web-fonts/plugin.css" rel="stylesheet">
<link href="{{asset('dashboard')}}/assets/plugins/select2/css/select2.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{asset('dashboard')}}/assets/plugins/multipleselect/multiple-select.css">
<link rel="stylesheet" href="{{asset('dashboard')}}/assets/plugins/datatable/css/jquery.dataTables.css"/>
<link rel="stylesheet" href="{{asset('dashboard')}}/assets/plugins/filepond/filepond.css"/>
<link rel="stylesheet" href="{{asset('dashboard')}}/assets/plugins/filepond/filepond-plugin-image-preview.css"/>

{{-- upload image --}}
<link href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" rel="stylesheet" type="text/css"/>


<link href="{{asset('dashboard')}}/assets/css/style.css" rel="stylesheet">
<link href="{{asset('dashboard')}}/assets/css/skins.css" rel="stylesheet">
<link href="{{asset('dashboard')}}/assets/css/colors/default.css" rel="stylesheet">
<link href="{{asset('dashboard')}}/assets/css/colors/color2.css" rel="stylesheet">
@toastr_css

<style>
    .alert-message {
        font-size: 15px !important;
        color: #666;
        /* font-family: "Open Sans", sans-serif; */
        font-weight: 400;
        font-size: 15px;
        text-align: center;
        margin-bottom: 35px;
        line-height: 1.6;
        align-self: center;
        font-size: 15px !important;
    }

    .check-div {
        display: flex;
        align-items: center;
        gap: 8px;
        margin-top: 6px;
    }

    .check-div input{
        width: 24px;
        height: 24px;
    }

    .check-div label {
        font-size: 21px;
        margin: 0;
        color: #f44336;
    }
</style>

{{-- cute-alert --}}
<link id="layoutstyle" rel="stylesheet" href="{{asset('toastr')}}/cute-alert.css">

@stack('admin_css')

resources/views/admin/inc/_loader.blade.php
<div id="global-loader">
    <svg version="1.1" id="L1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
            <circle fill="none" stroke="#824bab" stroke-width="6" stroke-miterlimit="15" stroke-dasharray="14.2472,14.2472" cx="50" cy="50" r="47">
                <animateTransform attributeName="transform" attributeType="XML" type="rotate" dur="5s" from="0 50 50" to="360 50 50" repeatCount="indefinite"></animateTransform>
            </circle>
        <circle fill="none" stroke="#cd96f7" stroke-width="1" stroke-miterlimit="10" stroke-dasharray="10,10" cx="50" cy="50" r="39">
            <animateTransform attributeName="transform" attributeType="XML" type="rotate" dur="5s" from="0 50 50" to="-360 50 50" repeatCount="indefinite"></animateTransform>
        </circle>
        <g fill="#fff">
            <rect x="30" y="35" width="5" height="30">
                <animateTransform attributeName="transform" dur="1s" type="translate" values="0 5 ; 0 -5; 0 5" repeatCount="indefinite" begin="0.1"></animateTransform>
            </rect>
            <rect x="40" y="35" width="5" height="30">
                <animateTransform attributeName="transform" dur="1s" type="translate" values="0 5 ; 0 -5; 0 5" repeatCount="indefinite" begin="0.2"></animateTransform>
            </rect>
            <rect x="50" y="35" width="5" height="30">
                <animateTransform attributeName="transform" dur="1s" type="translate" values="0 5 ; 0 -5; 0 5" repeatCount="indefinite" begin="0.3"></animateTransform>
            </rect>
            <rect x="60" y="35" width="5" height="30">
                <animateTransform attributeName="transform" dur="1s" type="translate" values="0 5 ; 0 -5; 0 5" repeatCount="indefinite" begin="0.4"></animateTransform>
            </rect>
            <rect x="70" y="35" width="5" height="30">
                <animateTransform attributeName="transform" dur="1s" type="translate" values="0 5 ; 0 -5; 0 5" repeatCount="indefinite" begin="0.5"></animateTransform>
            </rect>
        </g>
        </svg>
</div>

resources/views/admin/inc/back_to_top.blade.php
<a href="#top" id="back-to-top"><i class="fe fe-arrow-up"></i></a>

resources/views/admin/inc/main_footer.blade.php
<div class="main-footer text-center">
    <div class="container-fluid">
        <div class="row row-sm">
            <div class="col-md-12"> <span>Copyright © 2021 <a href="#">Codlop</a>. All rights reserved.</span>
            </div>
        </div>
    </div>
</div>

resources/views/admin/inc/page_header.blade.php
    <div>
        <h2 class="main-content-title tx-24 mg-b-5"> مرحبا بك في {{ setting('title') }}</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ aurl('/') }}">الرئيسية</a></li>
            @if($page_title)
                <li class="breadcrumb-item active" aria-current="page">{{ $page_title }}</li>
            @endif
        </ol>
    </div>

resources/views/admin/inc/side_menu.blade.php
<div class="main-sidebar main-sidebar-sticky side-menu">
    <div class="sidemenu-logo">
        <a class="main-logo" href="{{ aurl('/') }}">
            <img src="{{asset('dashboard')}}/assets/img/logo.svg" class="header-brand-img" alt="logo">
        </a>
    </div>
    <div class="main-sidebar-body">
        <ul class="nav">

            <li class="nav-item {{ in_array(request()->segment(2), ['slider', 'contract_advantage','polices','privacy','roles-conditions']) || ( in_array(request()->segment(2), ['site_text']) && request()->get('site_text_id') ) ? 'show active' : '' }}">
                <a class="nav-link with-sub" href="#">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-home sidemenu-icon"></i>
                    <span class="sidemenu-label">الصفحة الرئيسية</span>
                    <i class="angle fe fe-chevron-left"></i>
                </a>
                <ul class="nav-sub">
                    <li class="nav-sub-item {{ request()->segment(2) == 'slider' ? 'show active' : '' }}"><a class="nav-sub-link" href="{{ aurl('slider') }}">الاسلايدر</a></li>
                    @if(count(site_texts('home')) > 0)
                        @foreach(site_texts('home') as $site_text)
                            <li class="nav-sub-item {{ request()->get('site_text_id') == $site_text->id ? 'active' : '' }}"><a class="nav-sub-link" href="{{ aurl('site_text').'/'.$site_text->id.'/edit?page=home&site_text_id='.$site_text->id }}">{{ $site_text->title }}</a></li>
                        @endforeach
                    @endif
                    <li class="nav-sub-item {{ request()->segment(2) == 'contract_advantage' ? 'show active' : '' }}"><a class="nav-sub-link" href="{{ aurl('contract_advantage') }}">ميزات التعاقد</a></li>
                    <li class="nav-sub-item {{ request()->segment(2) == 'polices' ? 'show active' : '' }}"><a class="nav-sub-link" href="{{aurl('polices')}}">سياسه الإستخدام</a></li>
                    <li class="nav-sub-item {{ request()->segment(2) == 'privacy' ? 'show active' : '' }}"><a class="nav-sub-link" href="{{aurl('privacy')}}">سياسه الخصوصيه</a></li>
                    <li class="nav-sub-item {{ request()->segment(2) == 'roles-conditions' ? 'show active' : '' }}"><a class="nav-sub-link" href="{{route('roles-conditions.index')}}">الشروط و الأحكام</a></li>
                </ul>
            </li>

            <li class="nav-item {{ request()->segment(2)  == 'admin' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('admin') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-user sidemenu-icon"></i>
                    <span class="sidemenu-label">المشرفين</span>
                </a>
            </li>

            <li class="nav-item {{ request()->segment(2)  == 'teams' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('teams') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-user sidemenu-icon"></i>
                    <span class="sidemenu-label">فريق العمل</span>
                </a>
            </li>

            <li class="nav-item {{ request()->segment(2)  == 'settings' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('settings') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-settings sidemenu-icon"></i>
                    <span class="sidemenu-label">اعدادات الموقع</span></a>
            </li>

            <li class="nav-item {{ request()->segment(2) == 'site_text'  && !request()->get('site_text_id') ? 'show active' : '' }}">
                <a class="nav-link with-sub" href="#">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-text sidemenu-icon"></i>
                    <span class="sidemenu-label">نصوص الموقع</span>
                    <i class="angle fe fe-chevron-left"></i>
                </a>
                <ul class="nav-sub">
                    <li class="nav-sub-item {{ request()->segment(2) == 'site_text' ? 'active' : '' }}"><a class="nav-sub-link" href="{{ aurl('site_text') }}">نصوص الموقع</a></li>
                </ul>
            </li>

            <li class="nav-item {{ in_array(request()->segment(2), ['service', 'service_text'])  ? 'show active' : '' }}">
                <a class="nav-link with-sub" href="#">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-layout sidemenu-icon"></i>
                    <span class="sidemenu-label">الخدمات</span>
                    <i class="angle fe fe-chevron-left"></i>
                </a>
                <ul class="nav-sub">
                    <li class="nav-sub-item {{ in_array(request()->segment(2), ['service', 'service_text']) && !request()->get('service_id') ? 'active' : '' }}"><a class="nav-sub-link" href="{{ aurl('service') }}">ادارة الخدمات</a></li>
                    {{--<li class="nav-sub-item"><a class="nav-sub-link" href="{{ aurl('service/create') }}">اضافة خدمة جديدة</a></li>--}}
                    @if(count(all_services()) > 0)
                        @foreach(all_services() as $service)
                            <li class="nav-sub-item {{ request()->segment(2)  == 'service' && request()->get('service_id') == $service->id ? 'active' : '' }}"><a class="nav-sub-link" href="{{ aurl('service').'/'.$service->id.'/edit?page=home&service_id='.$service->id }}">{{ $service->title }}</a></li>
                        @endforeach
                    @endif
                </ul>
            </li>

            <li class="nav-item  {{ request()->segment(2)  == 'offer_detail' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('offer_detail') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-gift sidemenu-icon"></i>
                    <span class="sidemenu-label"> الأسعار و (الباقات)</span></a>
            </li>

            <li class="nav-item  {{ request()->segment(2)  == 'blog' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('blog') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-agenda sidemenu-icon"></i>
                    <span class="sidemenu-label">المدونة</span></a>
            </li>

            <li class="nav-item {{ request()->segment(2)  == 'language_allow' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('language_allow') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-world sidemenu-icon"></i>
                    <span class="sidemenu-label">اللغات</span></a>
            </li>

            <li class="nav-item {{ request()->segment(2)  == 'phone_code_allow' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('phone_code_allow') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-map-alt sidemenu-icon"></i>
                    <span class="sidemenu-label">الدول</span></a>
            </li>

            <li class="nav-item {{ request()->segment(2)  == 'contact' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('contact') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-headphone-alt sidemenu-icon"></i>
                    <span class="sidemenu-label">اتصل بنا</span></a>
            </li>

            <li class="nav-item  {{ request()->segment(2) == 'programs' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('programs') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-shopping-cart-full sidemenu-icon "></i>
                    <span class="sidemenu-label">خدمات اطلب الآن</span></a>
            </li>
            <li class="nav-item {{  in_array(request()->segment(2), ['user', 'user_program']) ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('user') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-user sidemenu-icon"></i>
                    <span class="sidemenu-label">العملاء</span></a>
            </li>

            <li class="nav-item {{  in_array(request()->segment(2), ['client']) ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('client') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-user sidemenu-icon"></i>
                    <span class="sidemenu-label">عملاء نفتخر بهم</span></a>
            </li>

            <li class="nav-item ">
                <a class="nav-link" href="{{route('invoices.index')}}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="fa fa-paper-plane sidemenu-icon"></i>
                    <span class="sidemenu-label">الفاتوره الالكترونيه </span></a>
            </li>

            <li class="nav-item  {{ request()->segment(2) == 'video_motion' ? 'show active' : '' }}">
                <a class="nav-link" href="{{ aurl('video_motion') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-agenda sidemenu-icon"></i>
                    <span class="sidemenu-label">اعمالنا</span></a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="{{ aurl('logout') }}">
                    <span class="shape1"></span>
                    <span class="shape2"></span>
                    <i class="ti-share sidemenu-icon"></i>
                    <span class="sidemenu-label">تسجيل خروج</span></a>
            </li>

        </ul>
    </div>
</div>

resources/views/admin/inc/there_is_no_elements_to_show.blade.php
<!-- NotFound -->
<div class="card">
    <div class="card-body">
        <div class="NotFound justify-content-center" style="max-width: 300px;margin: 0 auto;text-align: center;">
            <img src="{{asset('website')}}/default-images/not-found.jpg">
            <h3>لا يوجد عناصر لعرضها</h3>
        </div>
    </div>
</div>
<!-- NotFound -->